name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #*Icons
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0

  #*Architecture
  stacked: ^1.9.5
  stacked_services: ^0.7.2
  responsive_builder: ^0.3.0
  get_it: ^5.0.6
  injectable: ^1.1.2
  flutter_hooks: ^0.16.0

  #*Services
  url_launcher: ^6.0.2
  http: ^0.13.0

  #*Utilities
  collapsible_sidebar: ^1.0.7+2
  animated_text_kit: ^4.0.0
  simple_animations: ^2.5.1
  oktoast: ^3.0.0
  flutter_neumorphic:
  animations:
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 1.0.7
  auto_route_generator: 0.6.10
  build_runner: 1.11.1
  change_app_package_name:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
